### PR TITLE
Add public_agents_extra_volumes

### PR DESCRIPTION
**Pull request by jdef**
xref https://github.com/dcos-terraform/terraform-aws-public-agents/pull/9

### CODE REVIEW

**Comment by fatz** [comment]
@jdef https://github.com/dcos-terraform/terraform-aws-public-agents/tree/0.1.3

**Comment by jdef** [comment]
I suspect that CI is failing because co-dependent PR is missing: https://github.com/dcos-terraform/terraform-aws-dcos/pull/66

@fatz PTAL

**Comment by fatz** [comment]
thats solved. The integration test could be ignored we're working on this

**Comment by fatz** [comment]
@jdef can you try to resolve the conflict with the support branch.

We started with support branches for the different versions but where not yet able to change the default branch.

**Comment by jdef** [comment]
I don't know what this CI log means:
```
No such library resource com/mesosphere/global/terraform-file-dcos-terraform-test-examples/aws-0.1..x/ssh-key.pub could be found.[2019-06-05T15:44:55.447Z]
```

**Comment by fatz** [comment]
thats "fine" still a minor issue in the integration test.

**Pull request merged**
