### PR TITLE
IAM Profile added to the instances in this module

### PR DESCRIPTION
**Pull request by geekbass**
Add the ability to add IAM profile for each instance at this module level DCOS-45649

### CODE REVIEW

**Review by fatz — CHANGES_REQUESTED** [review]
this points me to another bug. dcos-iam is referenced in infrastructure but never used.

@geekbass can you please to a coalesce() with the new variable and the dcos-iam outputs

**Comment by geekbass** [comment]
ah yes! good catch! Adding request per @fatz

**Review by fatz — APPROVED** [review]
lgtm

**Comment by geekbass** [comment]
Merging per approval.

**Pull request merged**
